name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sunday at midnight UTC

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Specify a version, can be adjusted
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r config/requirements.txt
    - name: Run Trivy vulnerability scanner for filesystem
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'HIGH,CRITICAL' # Only fail for HIGH and CRITICAL vulnerabilities
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always() # Always run this step to upload results, even if previous steps fail
      with:
        sarif_file: 'trivy-results.sarif'

  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install pip-audit
      run: python -m pip install pip-audit
    - name: Run pip-audit
      run: pip-audit -r config/requirements.txt --strict --progress-spinner=off
      # Add `--fix` to automatically attempt to fix vulnerabilities, though this can be risky in CI
      # Consider adding `--ignore-vuln ID1 --ignore-vuln ID2` for known/accepted vulnerabilities

  static-analysis-bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Bandit
      run: pip install bandit
    - name: Run Bandit
      run: bandit -r . -ll -f sarif -o bandit-results.sarif || true
      # || true ensures the step doesn't fail the build, Bandit exits with non-zero if issues are found
      # We'll rely on the SARIF upload for visibility
    - name: Upload Bandit scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'bandit-results.sarif'
